"""add done field and add comment field

Revision ID: 6d2bbcffa4fe
Revises: 90d4d2660ff6
Create Date: 2022-02-24 15:07:14.194262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2bbcffa4fe'
down_revision = '90d4d2660ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('todos', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'comment')
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###
