"""add subtask table

Revision ID: c896cf9d9d74
Revises: 6d2bbcffa4fe
Create Date: 2022-02-24 15:33:45.986147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c896cf9d9d74'
down_revision = '6d2bbcffa4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
